name: CR Issue State Machine

on:
  issues:
    types: [opened, labeled, unlabeled, closed]

jobs:
  cr_state_machine:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Login to GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Transition on Issue Open
      if: github.event.action == 'opened'
      run: |
        gh issue edit ${{ github.event.issue.number }} --remove-label "Review" --remove-label "Analysis" --remove-label "Commit" --remove-label "Implement" --remove-label "Verification" --remove-label "Closed" --add-label "Submit"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Transition to Review on Label
      if: contains(github.event.issue.labels.*.name, 'Submit') && !contains(github.event.issue.labels.*.name, 'Review') && !contains(github.event.issue.labels.*.name, 'Analysis') && !contains(github.event.issue.labels.*.name, 'Commit') && !contains(github.event.issue.labels.*.name, 'Implement') && !contains(github.event.issue.labels.*.name, 'Verification') && !contains(github.event.issue.labels.*.name, 'Closed')
      run: |
        gh issue edit ${{ github.event.issue.number }} --remove-label "Submit" --add-label "Review"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Transition to Analysis on Review Approval
      if: contains(github.event.issue.labels.*.name, 'Review') && !contains(github.event.issue.labels.*.name, 'Submit') && !contains(github.event.issue.labels.*.name, 'Analysis') && !contains(github.event.issue.labels.*.name, 'Commit') && !contains(github.event.issue.labels.*.name, 'Implement') && !contains(github.event.issue.labels.*.name, 'Verification') && !contains(github.event.issue.labels.*.name, 'Closed')
      run: |
        gh issue edit ${{ github.event.issue.number }} --remove-label "Review" --add-label "Analysis"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Transition to Commit on Analysis Completion
      if: contains(github.event.issue.labels.*.name, 'Analysis') && !contains(github.event.issue.labels.*.name, 'Submit') && !contains(github.event.issue.labels.*.name, 'Review') && !contains(github.event.issue.labels.*.name, 'Commit') && !contains(github.event.issue.labels.*.name, 'Implement') && !contains(github.event.issue.labels.*.name, 'Verification') && !contains(github.event.issue.labels.*.name, 'Closed')
      run: |
        gh issue edit ${{ github.event.issue.number }} --remove-label "Analysis" --add-label "Commit"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Transition to Implement on Commit
      if: contains(github.event.issue.labels.*.name, 'Commit') && !contains(github.event.issue.labels.*.name, 'Submit') && !contains(github.event.issue.labels.*.name, 'Review') && !contains(github.event.issue.labels.*.name, 'Analysis') && !contains(github.event.issue.labels.*.name, 'Implement') && !contains(github.event.issue.labels.*.name, 'Verification') && !contains(github.event.issue.labels.*.name, 'Closed')
      run: |
        gh issue edit ${{ github.event.issue.number }} --remove-label "Commit" --add-label "Implement"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Transition to Verification on Implement
      if: contains(github.event.issue.labels.*.name, 'Implement') && !contains(github.event.issue.labels.*.name, 'Submit') && !contains(github.event.issue.labels.*.name, 'Review') && !contains(github.event.issue.labels.*.name, 'Analysis') && !contains(github.event.issue.labels.*.name, 'Commit') && !contains(github.event.issue.labels.*.name, 'Verification') && !contains(github.event.issue.labels.*.name, 'Closed')
      run: |
        gh issue edit ${{ github.event.issue.number }} --remove-label "Implement" --add-label "Verification"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Transition to Closed on Verification
      if: contains(github.event.issue.labels.*.name, 'Verification') && !contains(github.event.issue.labels.*.name, 'Submit') && !contains(github.event.issue.labels.*.name, 'Review') && !contains(github.event.issue.labels.*.name, 'Analysis') && !contains(github.event.issue.labels.*.name, 'Commit') && !contains(github.event.issue.labels.*.name, 'Implement') && !contains(github.event.issue.labels.*.name, 'Closed')
      run: |
        gh issue edit ${{ github.event.issue.number }} --remove-label "Verification" --add-label "Closed"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Handle Decline
      if: contains(github.event.issue.labels.*.name, 'Decline') && !contains(github.event.issue.labels.*.name, 'Submit') && !contains(github.event.issue.labels.*.name, 'Review') && !contains(github.event.issue.labels.*.name, 'Analysis') && !contains(github.event.issue.labels.*.name, 'Commit') && !contains(github.event.issue.labels.*.name, 'Implement') && !contains(github.event.issue.labels.*.name, 'Verification')
      run: |
        gh issue edit ${{ github.event.issue.number }} --remove-label "Verification" --remove-label "Decline" --add-label "Closed"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
